print("Hello, World!")
print()

print("UUU   " + "UUU   " + "TTTTTTTTT")
print(" U     " + "U    " + "T   " + "T   " + "T")
print(" U     " + "U        " + "T")
print(" U     " + "U        " + "T")
print(" U     " + "U        " + "T")
print("  UUUUU        " + "TTT")
print()

print("   /  " + "\\")
print("  /  " + "/ " + "\\")
print(" /  " + "/   " + "\\")
print(" \\  " "\\   " + "/")
print("  \\ _" + "\\_" + "/")
print("     \\" + "\\     "  "_ " +"_")
print("      \\" + "\\  " + "/   " + "/")
print("       \\" + "\\" + "/" + "_ _" + "/")
print("       //")
print()

print("One of my favorite songs is \"Cruel Summer\" by Taylor Swift.")
print()

print("I would like to visit:\nParis, France!")
